---
- name: Ensure system dependencies
  become: true
  ansible.builtin.package:
    name:
      - git
      - python3
      - python3-pip
      - python3-dev
      - openjdk-17-jdk
      - maven
      - gcc

- name: Get shell
  set_fact:
    _shell: "{{ ansible_user_shell | basename }}"

- name: Set user envvars
  become: true
  when: _shell != ""
  ansible.builtin.lineinfile:
    path: "~/.{{ _shell }}rc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: true
  loop:
    - regexp: "^(export )*JAVA_HOME"
      line: export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

- name: Upgrade pip
  become: true
  ansible.builtin.pip:
    name:
      - pip
    state: latest

- name: Install pip dependencies
  ansible.builtin.pip:
    name:
      - ansible
      - ansible-runner
      - wheel
    state: latest

- name: install ansible-rulebook
  environment:
    PIP_NO_BINARY: jpy
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  ansible.builtin.pip:
    name: ansible-rulebook
    state: latest

- name: install collections
  command: ansible-galaxy collection install community.general ansible.eda
